### ISSUE TITLE
chck in wlc doesn't seem to compile in Debian Stetch

### ISSUE THREAD

**Issue by n3rdopolis** [Cloudef/chck#18]
I think it might be because Debian uses ver 5 by default, and ver 5 tries to use CPP-2014... ...I think
I'm able to get it to build by running 
sed -i 's/-Wsuggest-attribute=const)/-Wsuggest-attribute=const -std=c11)/g' lib/chck/CMakeLists.txt

[  8%] Building C object lib/chck/chck/buffer/CMakeFiles/chck_buffer.dir/buffer.c.o
In file included from /srcbuild/wlc/lib/chck/chck/buffer/buffer.h:9:0,
                 from /srcbuild/wlc/lib/chck/chck/buffer/buffer.c:1:
/srcbuild/wlc/lib/chck/chck/buffer/endianess.h: In function ‘chck_bswap’:
/srcbuild/wlc/lib/chck/chck/buffer/endianess.h:108:4: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
    for (uint8_t *p = v; p < (uint8_t*)v + (memb * size); p += size)
    ^
/srcbuild/wlc/lib/chck/chck/buffer/endianess.h:108:4: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
/srcbuild/wlc/lib/chck/chck/buffer/buffer.c: In function ‘chck_buffer_compress_zlib’:
/srcbuild/wlc/lib/chck/chck/buffer/buffer.c:409:39: warning: passing argument 2 of ‘compress’ from incompatible pointer type
    while ((ret = compress(compressed, &dsize, buf->buffer, buf->size)) == Z_BUF_ERROR) {
                                       ^
In file included from /srcbuild/wlc/lib/chck/chck/buffer/buffer.c:8:0:
/usr/include/zlib.h:1160:21: note: expected ‘uLongf *’ but argument is of type ‘size_t *’
 ZEXTERN int ZEXPORT compress OF((Bytef *dest,   uLongf *destLen,
                     ^
/srcbuild/wlc/lib/chck/chck/buffer/buffer.c: In function ‘chck_buffer_decompress_zlib’:
/srcbuild/wlc/lib/chck/chck/buffer/buffer.c:461:43: warning: passing argument 2 of ‘uncompress’ from incompatible pointer type
    while ((ret = uncompress(decompressed, &dsize, buf->buffer, buf->size)) == Z_BUF_ERROR) {
                                           ^
In file included from /srcbuild/wlc/lib/chck/chck/buffer/buffer.c:8:0:
/usr/include/zlib.h:1197:21: note: expected ‘uLongf *’ but argument is of type ‘size_t *’
 ZEXTERN int ZEXPORT uncompress OF((Bytef *dest,   uLongf *destLen,
                     ^
lib/chck/chck/buffer/CMakeFiles/chck_buffer.dir/build.make:54: recipe for target 'lib/chck/chck/buffer/CMakeFiles/chck_buffer.dir/buffer.c.o' failed
make[2]: *** [lib/chck/chck/buffer/CMakeFiles/chck_buffer.dir/buffer.c.o] Error 1
CMakeFiles/Makefile2:1090: recipe for target 'lib/chck/chck/buffer/CMakeFiles/chck_buffer.dir/all' failed
make[1]: *** [lib/chck/chck/buffer/CMakeFiles/chck_buffer.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Cloudef** [comment]
Please post output without sedding the CMakeLists.txt, also related https://github.com/Cloudef/wlc/issues/62

**Comment by Cloudef** [comment]
You most likely have too old cmake. I've bumped the minimum to 3.1 which is needed for CMAKE_C_STANDARD. If you want to compile on older cmake, you need explicitly  -DCMAKE_C_FLAGS=-std=c99 when invoking cmake.
