### ISSUE TITLE
Test 7 fails

### ISSUE THREAD

**Issue by Fale** [Cloudef/chck#21]
Hi,
I'm trying to build chck for Fedora (I'm planning to make it an official Fedora package as well as wlc and sway).

Building I receive the following error:

          Start  7: dl_test
     7/14 Test  #7: dl_test ..........................***Exception: Other  0.02 sec

I'm attaching the whole root log and build log to ease the debug

[build.txt](https://github.com/Cloudef/chck/files/128700/build.txt)
[root.txt](https://github.com/Cloudef/chck/files/128699/root.txt)

**Comment by Cloudef** [comment]
Run the test again with `ctest -V -R dl_test` and post that output.

**Comment by Fale** [comment]
Attaching it :)
[build.txt](https://github.com/Cloudef/chck/files/128707/build.txt)

**Comment by Cloudef** [comment]
Does /usr/lib/libdl.so exist in your system? The test depends on that.

**Comment by Fale** [comment]
Being a 64bit os, I do not have that file, while I have /usr/lib64/libdl.so

**Comment by Cloudef** [comment]
All right, I should change that test get the path from CMake if possible.
