### ISSUE TITLE
Test 12 fails

### ISSUE THREAD

**Issue by Fale** [Cloudef/chck#22]
Hi,
I'm building chck for Fedora and it failed on Fedora 24 x86 and Fedora 23 x86_64 (while it was successful on Fedora 24 x86_64 and armv7hl, Fedora 23 x86 and armv7hl, and Fedora 25 for x86, x86_64 and armv7hl).

[This is the log of Fedora 24 x86](https://kojipkgs.fedoraproject.org//work/tasks/8348/13598348/build.log).
[This is the log of Fedora 23 x86_64](https://kojipkgs.fedoraproject.org//work/tasks/8363/13598363/build.log)

And more specifically:

    12: thread_queue_test: /builddir/build/BUILD/chck-2efd6cd314884712e9409e54c302afb9b9fff1b0/chck/thread/queue/test.c:36: destructor: Assertion `(item->a == 1 && item->c == 2) || (item->a == 2 && item->c == 1)' failed.

and:

    12 - thread_queue_test (Timeout)

Since it worked on many platforms but not that one specifically, what could be the cause.

**Comment by Cloudef** [comment]
Can you run the test manually under gdb and give me the output of bt full?

**Comment by Fale** [comment]
I'm closing this because I can not reproduce this any longer. In case this will occur again, I'll open a different bug
